#!/bin/bash
#

#############################################################
vm=rhel7.2
distro=http://download.eng.bos.redhat.com/rel-eng/latest-RHEL-7/compose/Server/x86_64/os/
optional=http://download.eng.bos.redhat.com/rel-eng/latest-RHEL-7/compose/Server/x86_64/os/
#############################################################
echo "
distro=$distro
vm=$vm
"
#############################################################
# - tidy up any prior installation of this VM
virsh destroy $vm
virsh undefine $vm --managed-save
virsh vol-delete --pool default /var/lib/libvirt/images/$vm.qcow2
virsh pool-refresh default
#############################################################
cat <<EOF > ks.cfg
# Kickstart file automatically generated by anaconda.

#version=DEVEL
install
url --url=$distro
lang en_US.UTF-8
keyboard us
network --onboot yes --device eth0 --bootproto dhcp
timezone --utc America/New_York
rootpw  redhat
selinux --enforcing
authconfig --enableshadow --passalgo=sha512
firewall --service=ssh
reboot

# The following is the partition information you requested
# Note that any partitions you deleted are not expressed
# here so unless you clear all partitions first, this is
# not guaranteed to work
zerombr
clearpart --linux --drives=vda

part pv.252002 --grow --size=500
volgroup vg --pesize=32768 pv.252002
logvol swap --name=lv_swap --vgname=vg --grow --size=2000 --maxsize=4000
logvol / --fstype=ext4 --name=lv_root --vgname=vg --grow --size=1024 --maxsize=51200
part /boot --fstype=ext4 --size=500

bootloader --location=mbr --timeout=5 --append="crashkernel=auto rhgb quiet console=ttyS0,115200"

%packages
@base
#@core
#@development tools
%end
EOF

#############################################################
pwd=$(pwd)
virt-install --name $vm --vcpus 2 --ram 2048 --vnc --location $distro --disk path=/var/lib/libvirt/images/$vm.qcow2,format=qcow2,size=8,bus=virtio --network bridge=virbr0,model=virtio --initrd-inject=$pwd/ks.cfg --extra-args "ks=file:/ks.cfg"
#############################################################

exit

