OVS-2.17-RHEL-8-Tests:"exec_of_rules exec_ovs_upgrade exec_sanity_check exec_topo_i40e exec_topo_ice exec_topo_mlx5_core_cx5 exec_topo_mlx5_core_cx6_dx exec_topo_mlx5_core_cx6_lx exec_topo_mlx5_core_bf2 exec_perf_ci_cx5 exec_perf_ci_cx6dx exec_perf_ci_cx6lx exec_endurance_cx6dx exec_endurance_cx6lx exec_topo_enic exec_topo_qede exec_topo_bnxt_en"

OVS-3.10-RHEL-8-Tests:"exec_of_rules exec_ovs_upgrade exec_sanity_check exec_topo_i40e exec_topo_ice exec_topo_mlx5_core_cx5 exec_topo_mlx5_core_cx6_dx exec_topo_mlx5_core_cx6_lx exec_topo_mlx5_core_bf2 exec_perf_ci_cx5 exec_perf_ci_cx6dx exec_perf_ci_bf2 exec_topo_enic exec_topo_qede exec_topo_bnxt_en"

OVS-2.17-RHEL-9-Tests:"exec_of_rules exec_ovs_upgrade exec_sanity_check exec_topo_ixgbe exec_topo_i40e exec_topo_ice exec_topo_mlx5_core_cx5 exec_topo_mlx5_core_cx6_dx exec_topo_mlx5_core_cx6_lx exec_topo_mlx5_core_bf2 exec_topo_arm exec_perf_ci_cx5 exec_perf_ci_cx6dx exec_perf_ci_bf2 exec_topo_enic exec_topo_qede exec_topo_bnxt_en"

OVS-3.10-RHEL-9-Tests:"exec_of_rules exec_ovs_upgrade exec_sanity_check exec_topo_i40e exec_topo_ice exec_topo_mlx5_core_cx5 exec_topo_mlx5_core_cx6_dx exec_topo_mlx5_core_cx6_lx exec_topo_mlx5_core_bf2 exec_topo_arm exec_perf_ci_cx5 exec_perf_ci_cx6lx exec_topo_enic exec_topo_qede exec_topo_bnxt_en"

OVS-3.20-RHEL-9-Tests:"exec_of_rules exec_ovs_upgrade exec_sanity_check exec_topo_i40e exec_topo_ice exec_topo_mlx5_core_cx5 exec_topo_mlx5_core_cx6_dx exec_topo_mlx5_core_cx6_lx exec_topo_mlx5_core_bf2 exec_topo_arm exec_perf_ci_cx5 exec_perf_ci_cx6lx exec_topo_enic exec_topo_qede exec_topo_bnxt_en"

# sanity check cards

#"exec_topo_enic exec_topo_qede exec_topo_bnxt_en"
